# import = ["/home/luis/.config/alacritty/custom-themes/MonochromeBlack.toml"]
# import = ["/home/luis/.config/alacritty/custom-themes/Solarized-Dark.toml"]
# import = ["/home/luis/.config/alacritty/custom-themes/gruvbox_dark.toml"]
# import = ["/home/luis/.config/alacritty/themes/rose-pine-dawn.toml"]
import = ["/home/luis/.cache/wal/colors-alacritty.toml"]

[cursor]
blink_interval = 400
blink_timeout = 0

[cursor.style]
blinking = "always"
shape = "Block"

[font]
size = 11.0

[font.bold]
family = "Gohu GohuFont"
# family = "terminus"
style = "Bold"

[font.normal]
# family = "terminus"
family = "Gohu GohuFont"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 6
y = 4
