# import = ["/home/luis/.config/alacritty/custom-themes/MonochromeBlack.toml"]
import = ["/home/luis/.config/alacritty/custom-themes/Solarized-Dark.toml"]
# import = ["/home/luis/.config/alacritty/custom-themes/gruvbox_dark.toml"]

[cursor]
blink_interval = 400
blink_timeout = 0

[cursor.style]
blinking = "always"
shape = "Block"

[font]
size = 11.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 6
y = 4
