  # Default colors
[colors.primary]
background= '#000000'
foreground= '#ffffff'


[colors.cursor]
text= '#000000'
cursor= '#ffffff'

[colors.normal]
black=   '#000000'
# red=   '#111111'
red=     '#444444'
green=   '#999999'
yellow=  '#333333'
blue=    '#888888'
magenta= '#555555'
cyan=    '#666666'
white=   '#777777'

# Bright colors
[colors.bright]
black=   '#090909'
red=     '#181818'
green=   '#272727'
yellow=  '#393939'
blue=    '#666666'
magenta= '#595959'
cyan=    '#707070'
white=   '#818181'
